### ISSUE TITLE
hongkiat.com - Images not loading

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#102]
PopupBlocker Dev (2.2.2) breaks image loading on the site (https://github.com/AdguardTeam/AdguardFilters/issues/13306).

[www.hongkiat.com-1522155751624.log](https://github.com/AdguardTeam/PopupBlocker/files/1852076/www.hongkiat.com-1522155751624.log)

**Comment by seanl-adg** [comment]
There has been a subtle yet crucial specification change for `RegExp.prototype.test` from ES5 to ES6.

The specification for ECMAScript 5 merely states that 	`RegExp.prototype.test` is equivalent to a result of `RegExp.prototype.exec` not being `null`.<sup>[1]</sup>

However, the specification for ECMAScript 6 explicitly states that `regex.test` internally __performs a property lookup__ `[[Get]](regex, "exec")` and use it instead of built-in `RegExp.prototype.exec`.<sup>[2]</sup> It seems that all the modern browsers already implemented this.

It is surprising that this fact seems to be nowhere explained, even in MDN. Somebody need to commit it in MDN.

In our code, we need to use `RegExp.prototype.exec` instead of `RegExp.prototype.test`, in order to make sure that our operation that is happening "under the membrane" never escape the membrane.

<sup>[1]</sup>https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.6.3
<sup>[2]</sup>https://www.ecma-international.org/ecma-262/6.0/#sec-regexpexec

**Comment by seanl-adg** [comment]
Should be fixed now by https://github.com/AdguardTeam/PopupBlocker/commit/dcb97290a9f3d43fa7f850bd611cfdd3c913fcad
