### ISSUE TITLE
Prevent background redirect

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/PopupBlocker#14]
Certain popunders open a current page in a new tab and navigates the current tab to an ad page.
Some of them are respectful to the hosting page, in that it does not navigates away the current tab when an attempt to open a new tab was unsuccessful. However, others are not, and they are using `window.location.href="..."` which we cannot really put any additional check onto.

I can think of following ways:
 - Use `beforeunload` event to allow users to choose whether to leave the page or not. Although it is not allowed to provide custom texts in beforeunload alerts, when blocked popup alerts are implemented, user may reasonably decide about it.
 - Set `window.location.href` again on `beforeunload` event, but it will still cause a refresh of a page. And possibly show a message "This page was refreshed to prevent redirection by popup scripts. Try this option for this website...."
 - Collect more information about the event handler by using `Function.caller`, and if it can be determined to be a disrespectful popunder, throws on the userscript to abort the popunder script.
 - Allow attempts to open popups with a first-party url, and when a parent window tries to navigate away, close the tab.
 - When a page tries to navigate away shortly after a popup is blocked, open a new window on `beforeunload` event with the url of the previously blocked popup request.
 - We can provide an option "Throw on suspicious popup attempts", which should not be enabled by default.

Here respectful/disrespectful is obviously about the publisher, not to site users. Popup/popunder scripts are supposed to cooperate with the publisher to earn them money, not sabotage the publisher's website by arbitrarily navigating away.
This issue can be reproduced on https://worldwidetorrents.eu/ with Chrome.

**Comment by seanl-adg** [comment]
Another idea:
 - When a background redirect happens shortly after a popup is blocked, store the domain where it happened in a persistant storage of userscript hosts, and when such site is re-visited, use a more aggressive blocking methods, such as throwing. This may be seen as a privacy concern for some users, because it stores a part of user's browsing history.

**Comment by seanl-adg** [comment]
A (partial) solution is implemented in https://github.com/AdguardTeam/PopupBlocker/pull/24.

While various solutions which require an additional user input such as manual blacklist of interacting with beforeunload prompt window can be implemented, we still need a _generic_ algorithm to prevent background redirects without user input.

One reliable way that has worked is to abort the popunder script execution before they use `location` apis. It tries to detect if a target url of a suspicious popup attempt is identical to the current url, or the link url if the clicked element is `<a>` tag. Such popups are marked as 'even more suspicious' and it is likely that a subsequent 'location' method call will navigate the current page away, so we throw in our scripts.

A challenge here is to detect target url; it is easy for a simple `window.open` call, which was the case of sample provided in the original post. However, it turned out that a popunder script found in https://github.com/AdguardTeam/PopupBlocker/issues/21 is doing something like `var win = window.open(''); win.location = '...'`. As a side note, this would be very hard to detect without the help of `Proxy` based implementation in dev version, since the original source code is heavily obfuscated and [my deobfuscator](https://seanl-adg.github.io/deob) is not yet ready for such kind of obfuscation scheme, so this is another justification of Proxy-based implementation. So, `Timeline` instance was extended with another detection module https://github.com/AdguardTeam/PopupBlocker/blob/ac0617ee7fdf6872f6bcda29bd25125961ca0d32/src/timeline/after/navigate-popup-to-itself.ts, and now it detects background redirect attempts in https://github.com/AdguardTeam/PopupBlocker/issues/21.
