### ISSUE TITLE
dailymotion.com - Login window blocked

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#30]
PopupBlocker blocks log in window If you try to log in with Google+ or Facebook:

![image](https://user-images.githubusercontent.com/10995998/29613439-4a667878-8806-11e7-872d-feaba5cd53a6.png)

http://www.dailymotion.com/us (Click on "SIGN IN" at top right)

**Comment by danidoedel** [comment]
Same on https://zattoo.com/start/signup (maybe related so I didn't open a new issue):

![image](https://user-images.githubusercontent.com/10995998/29662158-99efb916-88c6-11e7-9b18-851509c35e1f.png)

**Comment by seanl-adg** [comment]
These issues were caused by event delegation used by various frameworks. The first is caused by jQuery, and the second is caused by React.

The userscript currently relies a lot on a user click event's current target which marks to where the event has bubbled, but such event delegation makes it hard to reason about it. In the version 2.1.3, we implemented specific workarounds for jQuery and React.
