### ISSUE TITLE
False positive on google.com/analytics

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#36]
Video:
https://uploads.adguard.com/up04_cxpzp.mp4

Open https://www.google.com/analytics/ to reproduce it.

**Comment by seanl-adg** [comment]
This was caused by allowing [Google Tag Manager](https://www.google.com/analytics/tag-manager/) on google.com domain. When [auto-event tracking](https://support.google.com/tagmanager/answer/6106716) is enabled, on certain circumstances gtm calls `window.open` inside an event handler attached to `document`, hence it is considered suspicious. This problem can be more prominent when Popup Blocker is used without adblockers.

In 2.1.6 version, an workaround was implemented to recognize popups caused by gtm and to allow certain popup detection passes for such popups.
