### ISSUE TITLE
Compatibility with Firefox

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/PopupBlocker#40]
@seanl-adg 

1. Just a quick question, is the **beta** version of the userscript compatible with latest stable firefox release?

2. If yes, should the beta userscript perform the same in firefox as it performs in chrome?

**Comment by seanl-adg** [comment]
The distinction of release and beta channel is not what matters, if the userscript version you are using is higher than 2.1, it will be compatible with latest stable Firefox release, and it should perform almost the same level as in chrome. However, popup scripts typically do user agent sniffing and use different methods to open popups accordingly, so it can happen that a popup is blocked in the same page with Chrome but not in Firefox. If it happens, please report it so that we can fix it.

**Comment by The-Commissioner** [comment]
Ok wanted to clarify that only, I will report them tomorrow morning.
Thanx for your time.
