### ISSUE TITLE
Whitelisting issue on badoo.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#46]
STR:
1. register an account at badoo.com and log in
2. next window tells you to upload your photos, click on the following icon:

https://uploads.adguard.com/up05_i6z4e.png

3. Try to whitelist the blocked pop-up

Expected result: The pop-up has beed added to the whitelist. 
Actual result: Nothing happens.

![image](https://user-images.githubusercontent.com/17472907/31277398-75414b34-aaa9-11e7-9869-e7fa1b115be7.png)

Here's the video:

https://uploads.adguard.com/up05_4axfd.mp4

reported on our [forum](https://forum.adguard.com/index.php?threads/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D1%89%D0%B8%D0%BA%D0%BE%D0%BC-%D0%B2%D1%81%D0%BF%D0%BB%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B5%D0%B9-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D1%8B.25700/#post-154609), reproduced

**Comment by vozersky** [comment]
@seanl-adg please take a look

**Comment by seanl-adg** [comment]
There are 2 distinct issues here, the first one is a whitelisting issue and the second one is a popup detection false-positive.

The whitelisting issue is caused by the website's CSP policy conflicting with AG's websocket api, and the same issue was reported before https://github.com/AdguardTeam/AdguardForWindows/issues/1961.

The false-positive is caused by the website's own event delegation mechanism, and I don't see a straightforward way to detect it. I expect users to manually whitelist the website in such cases — maybe I should implement a default whitelist for popular websites.
