### ISSUE TITLE
slideshare.net - Mobile view: links blocked

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#49]
PopupBlocker 2.1.7
AdGuard for Windows 6.2.424.2123

https://www.slideshare.net/

Clicking on any link will result in an error and the link won't open. Normal desktop view of the page works fine.

![image](https://user-images.githubusercontent.com/10995998/31356843-ccbd71e2-ad3f-11e7-8f5b-5bc0a2c2607c.png)

**Comment by seanl-adg** [comment]
Thanks for reporting this issue. There are 2 issues: the first is a false-positive, and the second is an error that is shown in the screenshot you've uploaded.

Currently AG Android does not support userscripts, so Popup Blocker wasn't tested a lot on mobile devices, and I expect that we will need some work to make it work reliably on mobile devices.

The console error was caused by a code path that was supposed to be chosen when a popup is attached to touch events.

Regarding the false-postive issue, it is caused by [FastClick](https://github.com/ftlabs/fastclick) library that the website uses. It generates an artificial click when user touches somewhere, before the browser generates a click event. Due to its similarities with artificial clicks generated by popup/popunder scripts, it was detected as popups.

Now it seems that there are understandable reasons to create and dispatch an artificial events to the same target where the user has originally clicked or touched on, so I will add another check for this and allow artificial clicks for such cases.
