### ISSUE TITLE
Google Hangouts is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#63]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/7657

**Comment by seanl-adg** [comment]
The Hangouts extension's pop-up window contains an iframe to `hangouts.google.com`, and it calls `window.open` to obtain reference to a certain browsing context. Most of time this `hangouts.google.com` page loads very quickly, causing it to be caught by one of PopupBlocker's tests, that is meant to block calling `window.open` from a freshly loaded _empty_ iframes. Such technique is popular among popup/popunder scripts as a mean to open popups on Firefox.

Since popup/popunder scripts uses `about:blank` or `about:srcdoc` frames, this Hangouts extension's behavior can be distinguished from popup/popunder scripts by checking whether a fresh iframe has a non-empty url.

**Comment by seanl-adg** [comment]
Fixed in https://github.com/AdguardTeam/PopupBlocker/commit/d0efead535538c1fc3a520bcdaa50cf0f7b0290d
