### ISSUE TITLE
issue popup Adguard Blocker(NSFW)

### ISSUE THREAD

**Issue by missyoselin1** [AdguardTeam/PopupBlocker#71]
<h3>Issue URL </h3>
<a href="https://www.tmohentai.com/">https://www.tmohentai.com/</a>
<h3>Comment</h3>
<p>Username: <a href="https://github.com/missyoselin1" class="user-mention">@missyoselin1</a></p>
<blockquote>
<p>it does not let me write in the box of Search and newsletter !!  with Adguard Popup Blocker 2.1.10</p>
</blockquote>
<h3>Screenshots</h3>
<details>
  <summary>Screenshot 1</summary>
https://user-images.githubusercontent.com/24573008/34646751-99e16662-f33e-11e7-933d-9f5b01318555.png

</details>
<h3>System configuration</h3>
<table>
<thead>
<tr>
<th>Information</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr>
<td>Platform:</td>
<td>Win</td>
</tr>
<tr>
<td>AdGuard version:</td>
<td>6.2.437.2171</td>
</tr>
<tr>
<td>Browser:</td>
<td>Chrome</td>
</tr>
<tr>
<td>AdGuard driver:</td>
<td>TDI</td>
</tr>
<tr>
<td>Filters:</td>
<td>Russian,<br>English,<br>Spyware,<br>Social media,<br>Spanish/Portuguese,<br>Annoyances</td>
</tr>
<tr>
<td>Other extensions used:</td>
<td>Popup blocker adguard, AdsBypasser, Absolute Enable Right Click &amp; Copy.</td>
</tr></tbody></table>

**Comment by seanl-adg** [comment]
Hi, it seems that the issue is not relevant anymore. Please report again if the problem is still reproduced on your end.

I confirm that the issue was existed before, and I think that the cause will essentially be the same as https://github.com/AdguardTeam/PopupBlocker/issues/39, whose resolution would be somewhat complicated and dirty, and that's why it is not implemented yet. If you encounter similar issues somewhere please let us know.

**Comment by missyoselin1** [comment]
thank you!!
