### ISSUE TITLE
vc.ru - false positive

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#87]
https://vc.ru/33437-antireklamnye-itogi-2017-goda
Can't log in via social networks
![image](https://user-images.githubusercontent.com/8361299/36310417-9d630b58-1330-11e8-8e4c-56e578ec805b.png)

PopupBlocker beta.

**Comment by seanl-adg** [comment]
It seems that this websites uses a js framework which I can't find anywhere else, which includes event delegation mechanism. Should I add it to default whitelist?

**Comment by ameshkov** [comment]
Yes, let it be our default way to handle such incompatibilities.

Also, check https://tjournal.ru/ as well (the website is from the same devs).

**Comment by seanl-adg** [comment]
> let it be our default way to handle such incompatibilities.

I've been rather viewing it as a last resort.

The Popup Blocker should be (and has been) using a _generic_ algorithm to detect unwanted popups. If a false positive is discovered, I first try to understand what part of the detection logic is determining it as a unwanted popup, and then try to revise that logic to better distinguish the false positive and the real unwanted popups which the logic was supposed to catch.

I view this as a way how it can remain effective for vast range of undiscovered websites and for future websites. The more we resort to the default whitelist, the less effective it will be. 

In some case, the above ideal solution cannot be worked out due to lack of information that can be gathered via JS, and then we resort to the default whitelist. As of now, most of such cases fall into 2 categories:

 - A website uses some custom event delegation framework
 - A website does outbound link click tracking

My only concern is that this website [may not be popular](https://www.similarweb.com/website/vc.ru) in Russian web, so it may not be worth hardcoding it. What do you think @ameshkov ?

**Comment by ameshkov** [comment]
I was answering a question "Should I add it to default whitelist?"

We have two options: just do nothing or add it to the default whitelist.
My answer is: yes, add this to the default whitelist, and do this in similar cases.

**Comment by seanl-adg** [comment]
No, your answer was "Yes, let it be our default way to handle such incompatibilities.", and your subsequent answer was a posteriori justification of it.

**Comment by seanl-adg** [comment]
Fixed with https://github.com/AdguardTeam/PopupBlocker/commit/669c801a5b8b42fed2934543f9d48e8b1ae2c5f8
